package com.example.baseproject.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.baseproject.db.CommentBean;
import com.example.baseproject.db.HomeBean;
import com.example.baseproject.db.LinsecensBean;

import com.example.baseproject.db.CommentBeanDao;
import com.example.baseproject.db.HomeBeanDao;
import com.example.baseproject.db.LinsecensBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commentBeanDaoConfig;
    private final DaoConfig homeBeanDaoConfig;
    private final DaoConfig linsecensBeanDaoConfig;

    private final CommentBeanDao commentBeanDao;
    private final HomeBeanDao homeBeanDao;
    private final LinsecensBeanDao linsecensBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commentBeanDaoConfig = daoConfigMap.get(CommentBeanDao.class).clone();
        commentBeanDaoConfig.initIdentityScope(type);

        homeBeanDaoConfig = daoConfigMap.get(HomeBeanDao.class).clone();
        homeBeanDaoConfig.initIdentityScope(type);

        linsecensBeanDaoConfig = daoConfigMap.get(LinsecensBeanDao.class).clone();
        linsecensBeanDaoConfig.initIdentityScope(type);

        commentBeanDao = new CommentBeanDao(commentBeanDaoConfig, this);
        homeBeanDao = new HomeBeanDao(homeBeanDaoConfig, this);
        linsecensBeanDao = new LinsecensBeanDao(linsecensBeanDaoConfig, this);

        registerDao(CommentBean.class, commentBeanDao);
        registerDao(HomeBean.class, homeBeanDao);
        registerDao(LinsecensBean.class, linsecensBeanDao);
    }
    
    public void clear() {
        commentBeanDaoConfig.clearIdentityScope();
        homeBeanDaoConfig.clearIdentityScope();
        linsecensBeanDaoConfig.clearIdentityScope();
    }

    public CommentBeanDao getCommentBeanDao() {
        return commentBeanDao;
    }

    public HomeBeanDao getHomeBeanDao() {
        return homeBeanDao;
    }

    public LinsecensBeanDao getLinsecensBeanDao() {
        return linsecensBeanDao;
    }

}
